name: Automatic Pull Request Creation
on:
  push:
    branches:
        - "**"
      
permissions:
  contents: write
  pull-requests: write


jobs:
    criar-pr-automatico:
        if: github.ref != 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Criar pull request
          run: |
            gh pr create \
            --title "${{ github.event.head_commit.message }}" \
            --body "PR automático criado pelo workflow" \
            --base main \
            --head "${{ github.ref_name }}" || true
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}